version: '3.8'

services:

  app-etl:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/opt
      - ./requirements.txt:/opt/requirements.txt
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db 
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: ["airflow", "standalone"]

