CREATE TABLE pda."2024_jorge_roberto_rearte_carvalho_schema".flight_events_history (
    id VARCHAR(20),
    callsign VARCHAR(20),
    number_default VARCHAR(20),
    generic_status_text VARCHAR(50),
    generic_status_type VARCHAR(50),
    generic_eventtime_utc TIMESTAMP,
    generic_eventtime_local TIMESTAMP,
    countryid VARCHAR(10),
    registration VARCHAR(10),
    model_code VARCHAR(20),
    code_iata VARCHAR(10),
    origin_code_iata VARCHAR(10),
    origin_position_latitude DOUBLE PRECISION,
    origin_position_longitude DOUBLE PRECISION,
    origin_position_altitude DOUBLE PRECISION,
    destination_code_iata VARCHAR(10),
    destination_position_latitude DOUBLE PRECISION,
    destination_position_longitude DOUBLE PRECISION,
    destination_position_altitude DOUBLE PRECISION,
    scheduled_departure TIMESTAMP,
    scheduled_arrival TIMESTAMP,
    real_departure TIMESTAMP,
    real_arrival TIMESTAMP,
    estimated_departure TIMESTAMP,
    estimated_arrival TIMESTAMP,
    historical_flighttime DOUBLE PRECISION,
    historical_delay DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    altitude DOUBLE PRECISION,
    speed DOUBLE PRECISION,
    capture_datetime_utc TIMESTAMP,
    heading DOUBLE PRECISION
);
