CREATE TABLE <db>.<schema_name>.flights (
	id varchar(20),
	row varchar(20),
	callsign varchar(20),
	number_default varchar(20),
	number_alternative varchar(20),
	live boolean,
	text varchar(20),
	icon varchar(20),
	estimated varchar(20),
	ambiguous boolean,
	generic_status_text varchar(20),
	generic_status_color varchar(20),
	generic_status_type varchar(20),
	generic_eventTime_utc timestamp,
	generic_eventTime_local timestamp,
	countryId varchar(10),
	registration varchar(10),
	age varchar(20),
	msn varchar(20),
	hex varchar(20),
	model_code varchar(20),
	model_text varchar(20),
	name varchar(20),
	short varchar(20),
	url varchar(20),
	code_iata varchar(20),
	code_icao varchar(20),
	real varchar(20),
	origin_name varchar(100),
	origin_code_iata varchar(10),
	origin_code_icao varchar(10),
	origin_position_latitude double precision,
	origin_position_longitude double precision,
	origin_position_altitude double precision,
	origin_position_country_id integer,
	origin_position_country_name varchar(50),
	origin_position_country_code varchar(10),
	origin_position_region_city varchar(100),
	origin_timezone_name varchar(200),
	origin_timezone_offsetHours varchar(5),
	origin_timezone_isDst boolean,
	origin_visible boolean,
	origin_website varchar(50),
	origin_info_terminal varchar(50),
	origin_info_baggage varchar(50),
	origin_info_gate varchar(50),
	destination_name varchar(50),
	destination_code_iata varchar(50),
	destination_code_icao varchar(50),
	destination_position_latitude double precision,
	destination_position_longitude double precision,
	destination_position_altitude double precision,
	destination_position_country_id integer,
	destination_position_country_name varchar(50),
	destination_position_country_code varchar(10),
	destination_position_country_codeLong varchar(10),
	destination_position_region_city varchar(50),
	destination_timezone_name varchar(50),
	destination_timezone_offsetHours varchar(5),
	destination_timezone_isDst boolean,
	destination_visible boolean,
	destination_website varchar(50),
	destination_info_terminal varchar(50),
	destination_info_baggage varchar(50),
	destination_info_gate varchar(50),
	origin_position_country_codeLong varchar(50),
	scheduled_departure timestamp,
	scheduled_arrival timestamp,
	real_departure timestamp,
	real_arrival timestamp,
	estimated_departure timestamp,
	estimated_arrival timestamp,
	other_eta timestamp,
	other_updated timestamp,
	historical_flighttime double precision,
	historical_delay double precision,
	latitude double precision,	
	longitude double precision,	
	altitude double precision,	
	speed double precision,	
	capture_datetime timestamp,	
	heading double precision
);